import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='container m-auto w-full min-h-screen flex flex-col justify-center items-center'>
          <h1 className='text-8xl'>
            Howdy
          </h1>
        </div>
      </main>
    </div>
  )
}

export default Home
